### PR TITLE
fix #42 (RESTConnector) : json simple value causes exception

### LINKED ISSUE #42: Json simple values causes exception
We have a web service that returns a numeric value as a response.
The REST connector assumes that the response is either an array of objets or an object, in this case trying to deserialize json into a Map which is resulting in an exception.

The connector should not raise an exception when the response is a simple value (string, number, null, true, false, date).

### PR DESCRIPTION
**Pull request by cjundt**
Check if json is an object type before trying to deserialize it into a Map.

Closes #42

### CODE REVIEW

File: src/main/java/org/bonitasoft/connectors/rest/RESTConnector.java [hunk 1]
```diff
@@ -412,8 +412,15 @@ private void setOutputs(final HttpResponse response, Request request) throws IOE
                         if (contentType != null
                                 && !Strings.isNullOrEmpty(contentType.getValue())
                                 && contentType.getValue().toLowerCase().contains("json")) {
-                            setBody(new ObjectMapper().readValue(bodyResponse,
-                                    bodyResponse.startsWith("[") ? List.class : HashMap.class));
+                            if (bodyResponse.startsWith("[")) {
```
Comment (rbioteau) [inline src/main/java/org/bonitasoft/connectors/rest/RESTConnector.java]: I would use a try/catch instead of an if statement here.
Something like
```
try{
      setBody(new ObjectMapper().readValue(bodyResponse,
                            bodyResponse.startsWith("[") ? List.class : HashMap.class));
}catch (JsonParseException | JsonMappingException e) {
     LOGGER.warning(String.format(
                     "bodyAsObject output cannot be set. Response content is not valid json(%s).",
                      bodyResponse));
 }
```

This way it covers more failures cases.

File: src/main/java/org/bonitasoft/connectors/rest/RESTConnector.java [hunk 2]
```diff
@@ -412,8 +412,15 @@ private void setOutputs(final HttpResponse response, Request request) throws IOE
...
+                                setBody(new ObjectMapper().readValue(bodyResponse, List.class));
+                            } else if(bodyResponse.startsWith("{")) {
+                                setBody(new ObjectMapper().readValue(bodyResponse, HashMap.class));
+                            } else { 
+                                LOGGER.warning(String.format(
+                                    "Body as map output cannot be set. Response content is not valid json(%s).",
```
Comment (rbioteau) [inline src/main/java/org/bonitasoft/connectors/rest/RESTConnector.java]:
```suggestion
                                    "bodyAsObject output cannot be set. Response content is not valid json(%s).",
```

File: src/test/java/org/bonitasoft/connectors/rest/RESTConnectorTest.java [hunk 3]
```diff
@@ -472,6 +472,106 @@ public void should_retrieve_response_as_a_Map_jsonContentType() throws BonitaExc
...
+    }
+
+    /**
+     * Test the json simple null value
+     * 
+     * @throws BonitaException exception
+     * @throws InterruptedException exception
+     */
+    @Test
+    public void json_simple_null_value_should_not_raise_exception() throws BonitaException, InterruptedException {
```
Comment (rbioteau) [inline src/test/java/org/bonitasoft/connectors/rest/RESTConnectorTest.java]: `null` is not a valid JSON text. It should fail with a warning like other invalid json response.

File: src/main/java/org/bonitasoft/connectors/rest/RESTConnector.java [hunk 4]
```diff
@@ -412,8 +412,15 @@ private void setOutputs(final HttpResponse response, Request request) throws IOE
...
+                                    bodyResponse));
+                            }
                         } else {
                             LOGGER.warning(String.format(
                                     "Body as map output cannot be set. Response content type is not json compliant(%s).",
```
Comment (rbioteau) [inline src/main/java/org/bonitasoft/connectors/rest/RESTConnector.java:432]:
```suggestion
                                    "bodyAsObject output cannot be set. Response content type is not json compliant(%s).",
```

**Review by rbioteau — CHANGES_REQUESTED** [review]
Thanks a lot for the contribution, I made some change request.
Before merging your PR we need to set up a CLA on the repository that you'll need to approve.

File: src/main/java/org/bonitasoft/connectors/rest/RESTConnector.java (hunk 1 above)
Comment (cjundt) [reply src/main/java/org/bonitasoft/connectors/rest/RESTConnector.java]: Made a new commit with try/catch AND the if statment because I also want to handle the case of simple values.

File: src/main/java/org/bonitasoft/connectors/rest/RESTConnector.java (hunk 2 above)
Comment (cjundt) [reply src/main/java/org/bonitasoft/connectors/rest/RESTConnector.java]: done

File: src/test/java/org/bonitasoft/connectors/rest/RESTConnectorTest.java (hunk 3 above)
Comment (cjundt) [reply src/test/java/org/bonitasoft/connectors/rest/RESTConnectorTest.java]: "null" is valid, see https://www.json.org/json-en.html and it's handled as expected in the test case.

Comment (rbioteau) [reply src/test/java/org/bonitasoft/connectors/rest/RESTConnectorTest.java]: Fair enough 👍

File: src/main/java/org/bonitasoft/connectors/rest/RESTConnector.java (hunk 1 above)
Comment (rbioteau) [reply src/main/java/org/bonitasoft/connectors/rest/RESTConnector.java]: 👍

**Review by rbioteau — APPROVED** [review]

**Comment by rbioteau** [comment]
Fix integrated for Bonita 7.11
